package com.example.album_project.enums;

public enum PhotoType {

    LANDSCAPE, WILDLIFE, MACRO, UNDERWATER, ASTROPHOTOGRAPHY, AERIAL, SCIENTIFIC, PORTRAITS, WEDDING,
    DOCUMENTARY, SPORTS, FASHION, COMMERCIAL, STREET, EVENT, TRAVEL, PET,PRODUCT, FOOD, ARCHITECTURE

}
